Course & Section API with full Docker support
SiGMobileUIUC/OnePlace-Illinois-API pull request #2
Opened 2021-07-17 04:11 UTC by jwparktom

(1) Course & section data is now parsed from CSV files (e.g. data/2021-fa.csv) and stored into local Postgres.

Docker now works by `docker compose up --build -d` (to rebuild). Every time Docker (re)starts, it parses the CSV files, which is fairly fast.

(2) API now includes `/api/v1/section/search`

Example of 'section' API: `/api/v1/section/search?code=CS124`

```
{
    "sections": [
        {
            "year": 2021,
            "term": "fall",
            "CRN": 74481,
            "full_code": "CS_124_74481",
            "course": "CS_124",
            "code": "ABA",
            "title": "",
            "info": "Credit is not given for both CS 124 and CS 125. Prerequisite: Three years of high school mathematics or MATH 112.",
            "part_of_term": "1",
            "credit_hours": "3 hours.",
            "section_status": "A",
            "enrollment_status": "Open (Restricted)",
            "type": "Online Lab",
            "type_code": "OLB",
            "start_time": "09:00 AM",
            "end_time": "09:50 AM",
            "days_of_week": "T",
            "room": "",
            "building": "",
            "instructors": ""https://guides.github.com/features/mastering-markdown/
        },
        ...
    ]
}
```

Example of 'course' API: `/api/v1/course/search?keyword=CS 124`

```
{
    "courses": [
        {
            "subjectId": "CS",
            "subjectNumber": 124,
            "name": "Introduction to Computer Science I"
        },
        ...
    ]
}
```

Use the course code retrieved from course API to request further data from section API. Responses will be pretty fast since it's all on local Postgres.

Example flow:
- User searches "CS 124" => App requests `/api/v1/course/search?keyword=CS 124`
- Server returns data & App caches and renders data
- User clicks on the course "CS 124" => App requests `/api/v1/section/search?code=CS124` (no spacing)
- Server returns data & App caches and renders data

2021-07-17 17:48 UTC, rahulshamkuwar requested changes
Could you also change what the `course` request returns? Since we have already scraped the data from the XML, it would be better to send all the details back... cuz right the app uses what you send back and makes an XML request, which is pointless since the CSV has that data.

At least return the following properties, which are part of the `CourseItem` model:

```
Course {
/// ns2:course -> parents -> calendarYear id
  int? year;

  /// ns2:course -> parents -> term
  Semester? semester;

  /// ns2:course -> parents -> term id
  int? semesterID;

  /// ns2:course -> parents -> subject
  String subject;

  /// ns2:course -> parents -> subject id
  String subjectID;

  /// ns2:course -> id
  int? courseID;

  /// ns2:course -> label
  String title;

  /// ns2:course -> description
  String description;

  /// ns2:course -> creditHours
  String creditHours;

  /// ns2:course -> courseSectionInformation
  String? courseSectionInformation;

  /// ns2:course -> classScheduleInformation
  String? classScheduleInformation;

  /// ns2:course -> sections
  List<String> sectionsLinks;

  /// ns2:course -> genEdCategories -> category -> description
  List<String?>? categories;

}

```

2021-07-17 18:16 UTC, jwparktom commented
Yup, I'll add query option "onlyCourses" and set it to default: false. False => returns course & section data. True => returns only course data.

2021-07-18 22:03 UTC, jwparktom commented
**Updated Course API parameters**:
- per_page (INTEGER): how many courses to show per page (DEFAULT: 15) (MIN: 10) (MAX: 30)
- page (INTEGER): which page to show (DEFAULT: 1) (MIN: 1)
- only_courses (BOOL): show just the course data (DEFAULT: false)

(1) **per_page** and **page**: Added to speed up the response. Otherwise, the server would have to get all sections for all courses related to the given keyword. And frankly, I don't think users would need more than 15 courses shown before picking the right one.
(2) **only_courses**: Added for scenarios when the page only needs to render course data. `default: false` returns the data of all sections of the course.

**Updated Course API Response**: `/api/v1/course/search?keyword=CS 124`
```
{
    "courses": [
        {
            "subjectId": "CS",
            "subjectNumber": 124,
            "name": "Introduction to Computer Science I",
            "sections": [
                {
                    "year": 2021,
                    "term": "fall",
                    "CRN": 74481,
                    "code": "ABA",
                    "title": "",
                    "info": "Credit is not given for both CS 124 and CS 125. Prerequisite: Three years of high school mathematics or MATH 112.",
                    "part_of_term": "1",
                    "credit_hours": "3 hours.",
                    "section_status": "A",
                    "enrollment_status": "Open (Restricted)",
                    "type": "Online Lab",
                    "type_code": "OLB",
                    "start_time": "09:00 AM",
                    "end_time": "09:50 AM",
                    "days_of_week": "T",
                    "room": "",
                    "building": "",
                    "instructors": ""
                },
                ... (more sections)
            ]
        },
        ... (more courses)
    ]
}
```

2021-07-18 22:23 UTC, rahulshamkuwar approved these changes

2021-07-18 22:24 UTC, merged